# Generated by Django 5.2.5 on 2025-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songstable',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
