# Generated by Django 5.2.5 on 2025-08-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_songstable_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongsTable',
            new_name='Songs',
        ),
    ]
