# Generated by Django 5.2.5 on 2025-08-13 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_songstable_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='signer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.singer'),
            preserve_default=False,
        ),
    ]
