# Generated by Django 5.2.5 on 2025-08-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_songs_signer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='signer',
            new_name='singer',
        ),
    ]
